const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const loadApp=require('./load-app.cjs');
function localized(){const a=loadApp();const file=path.join(__dirname,'../assets/i18n.js');assert.ok(fs.existsSync(file),'localization runtime exists');a.run('document.documentElement={lang:"zh-CN"};window.DEVKIT_LOCALE='+fs.readFileSync(path.join(__dirname,'../content/zh-CN/ui.json'),'utf8'));a.run('window.DEVKIT_LOCALE={ui:window.DEVKIT_LOCALE,http:'+fs.readFileSync(path.join(__dirname,'../content/zh-CN/http-status.json'),'utf8')+'}');a.run(fs.readFileSync(file,'utf8'));return a;}
test('Chinese tool status preserves JSON and literal conversion output',()=>{const a=localized();const raw='{"Input":"Done.","id":9007199254740993}';a.get('#json-in').value=raw;a.run('jsonAction("minify")');assert.match(a.get('#json-msg').innerHTML,/有效/);assert.match(a.get('#json-out').innerHTML,/Input/);assert.match(a.get('#json-out').innerHTML,/9007199254740993/);a.get('#b64-in').value='Done.';a.run('b64Action("enc")');assert.equal(a.get('#b64-out').value,'RG9uZS4=');assert.equal(a.get('#b64-msg').innerHTML,'已完成。');});
test('Chinese cron describes OR semantics and relative times',()=>{const a=localized();a.get('#cron-expr').value='0 9 1 * MON';a.run('cronRun()');assert.match(a.get('#cron-desc').textContent,/或/);assert.match(a.get('#cron-desc').textContent,/周一/);assert.match(a.get('#cron-msg').textContent,/有效/);assert.match(a.run('relTime(new Date(Date.now()+120000))'),/分钟/);});
test('Chinese JWT claims and regex labels do not translate payload or matches',()=>{const a=localized();a.get('#jwt-in').value=Buffer.from('{"alg":"HS256"}').toString('base64url')+'.'+Buffer.from('{"name":"EXPIRED","exp":1}').toString('base64url')+'.x';a.run('jwtDecode()');assert.match(a.get('#jwt-claims').innerHTML,/已过期/);assert.match(a.get('#jwt-payload').innerHTML,/EXPIRED/);a.run('renderRegexResult({matches:[{index:0,text:"Index",groups:["Groups"],named:{}}],truncated:false},"Index")');assert.match(a.get('#rx-msg').textContent,/匹配/);assert.match(a.get('#rx-matches').innerHTML,/索引/);assert.match(a.get('#rx-matches').innerHTML,/Groups/);});
test('Chinese errors are localized at UI boundary, English algorithms unchanged',()=>{const a=localized();a.get('#curl-src').value='bash';a.get('#curl-dst').value='pwsh';a.get('#curl-in').value='curl $URL';a.run('curlConvert()');assert.match(a.get('#curl-msg').textContent,/变量/);assert.throws(()=>a.run('tokenizeCurl("curl $URL","bash")'),/Variable expansion/);a.get('#json-in').value='{bad';a.run('jsonAction("format")');assert.match(a.get('#json-msg').innerHTML,/JSON 语法/);});
test('Chinese HTTP search returns localized descriptions with standard code and name',()=>{const a=localized();const rendered=[];a.get('#http-list').appendChild=node=>rendered.push(node.innerHTML);a.get('#http-search').value='缓存';a.run('renderHttp()');assert.equal(rendered.length,1);assert.match(rendered[0],/304/);assert.match(rendered[0],/Not Modified/);assert.match(rendered[0],/缓存副本/);assert.equal(a.run('HTTP_STATUS.every(([code])=>Object.hasOwn(window.DEVKIT_LOCALE.http,code))'),true);});
test('runtime English fallback preserves exact existing status wording',()=>{const a=localized();a.run('document.documentElement.lang="en"');a.get('#json-in').value='{"x":1}';a.run('jsonAction("format")');assert.equal(a.get('#json-msg').innerHTML,'Valid JSON · formatted with 2-space indent. Original numbers and keys preserved.');assert.equal(a.run('uiError(new Error("Unterminated quoted argument."))'),'Unterminated quoted argument.');assert.equal(a.run('window.DevKitI18n.cronExplain({},"Every minute · every day")'),'Every minute · every day');assert.equal(a.run('window.DevKitI18n.relativeTime(-1000,1,"second","-1 second")'),'-1 second');});
test('Chinese error paths and internationalized numeric outputs retain original values',()=>{const a=localized();a.get('#ts-input').value='invalid';a.run('refreshTimestamp()');assert.equal(a.get('#ts-local').textContent,'输入无效');a.get('#url-in').value='%zz';a.get('#url-mode').value='component';a.run('urlAction("dec")');assert.match(a.get('#url-msg').innerHTML,/百分号编码/);a.get('#b64-in').value='/w==';a.run('b64Action("dec")');assert.match(a.get('#b64-msg').innerHTML,/解码失败/);a.get('#cidr-in').value='192.168.1.3/24';a.run('cidrRun()');assert.equal(a.get('#cidr-net').textContent,'192.168.1.0/24');assert.equal(a.get('#cidr-hosts').textContent,'254');a.get('#color-in').value='#f00';a.run('colorConvert()');assert.equal(a.get('#color-rgb').textContent,'rgb(255, 0, 0)');a.get('#ent-in').value='Input & Done.';a.run('entAction("enc")');assert.equal(a.get('#ent-out').value,'Input &amp; Done.');a.run('window.crypto=null;uuidGen(1)');assert.match(a.get('#uuid-msg').textContent,/安全随机源/);});
